# example config for camera video to JSmpeg (V4L2 -> MPEG1 -> WebSocket)

streams:
- source:
    type: "v4l2"
    device: "/dev/video0"
    width: 1280
    height: 720
    fps: 30
  
  decoder:
    type: "none"
  
  encoder:
    type: "mpeg1sw"
    bitrate: 3000
    tsmux_alignment: 50
  sink:
    type: "ws"
    host: "0.0.0.0"
    port: 8765
    queue_size: 10
